//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using QF;
    using UnityEngine;
    
    public class GameScenePrefabData : QFramework.UIPanelData
    {
    }
    
    public partial class GameScenePrefab : QFramework.UIPanel,ISingleton
    {
        public static GameScenePrefab Instance
        {
            get { return MonoSingletonProperty<GameScenePrefab>.Instance; }
        }
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as GameScenePrefabData ?? new GameScenePrefabData();

        }
        Transform[] mChildArr;

        private void Start()
        {
            mChildArr = GetComponentsInChildren<Transform>();

        }

        public void SetActiveAll() {
            foreach (Transform item in mChildArr)
            {
                item.gameObject.SetActive(true);
            }
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }

        public void OnSingletonInit()
        {
           
        }
    }
}
