//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using QF;
    using QF.Res;
    using QFramework;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class MyMotaUIHomePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class MyMotaUIHomePanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as MyMotaUIHomePanelData ?? new MyMotaUIHomePanelData();

            SendMsg(new AudioMsgWithBool((ushort)AudioEvent.MusicSwitch, true));
            SendMsg(new AudioMusicMsg("start"));
        }

        protected override void RegisterUIEvent()
        {
            BtnStart.onClick.AddListener(() =>
            {
                CloseSelf();
                PlayerData.Instance.NewGame.Value = true;
                UIMgr.OpenPanel<MyMotaUIGamePanel>();
            });
        }
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
