//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class MyMotaUIGamePanel
    {
        
        public const string NAME = "MyMotaUIGamePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text Name;
        
        [SerializeField()]
        public UnityEngine.UI.Text CurrntFloor;
        
        [SerializeField()]
        public UnityEngine.UI.Text Level;
        
        [SerializeField()]
        public UnityEngine.UI.Text Life;
        
        [SerializeField()]
        public UnityEngine.UI.Text Attack;
        
        [SerializeField()]
        public UnityEngine.UI.Text Defend;
        
        [SerializeField()]
        public UnityEngine.UI.Text Experience;
        
        [SerializeField()]
        public UnityEngine.UI.Text Gold;
        
        [SerializeField()]
        public UnityEngine.UI.Text YellowKey;
        
        [SerializeField()]
        public UnityEngine.UI.Text RedKey;
        
        [SerializeField()]
        public UnityEngine.UI.Text PurpleKey;
        
        [SerializeField()]
        public UnityEngine.UI.Text Extend;
        
        [SerializeField()]
        public MenuPanel MenuPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Image GuidePanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnContinue;
        
        [SerializeField()]
        public npc2_0Panel npc2_0Panel;
        
        [SerializeField()]
        public npc2_4Panel npc2_4Panel;
        
        [SerializeField()]
        public npc2_12Panel npc2_12Panel;
        
        [SerializeField()]
        public npc2_8Panel npc2_8Panel;
        
        [SerializeField()]
        public FloorPanel FloorPanel;
        
        private MyMotaUIGamePanelData mPrivateData = null;
        
        public MyMotaUIGamePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new MyMotaUIGamePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Name = null;
            CurrntFloor = null;
            Level = null;
            Life = null;
            Attack = null;
            Defend = null;
            Experience = null;
            Gold = null;
            YellowKey = null;
            RedKey = null;
            PurpleKey = null;
            Extend = null;
            MenuPanel = null;
            GuidePanel = null;
            BtnContinue = null;
            npc2_0Panel = null;
            npc2_4Panel = null;
            npc2_12Panel = null;
            npc2_8Panel = null;
            FloorPanel = null;
            mData = null;
        }
    }
}
