//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using QF.Extensions;
    using QF.Res;
    using System.Linq;
    using UniRx;
    using UnityEngine;

    public class MyMotaUIGamePanelData : QFramework.UIPanelData
    {
        public PlayerData Model = new PlayerData ();
    }

    public partial class MyMotaUIGamePanel : QFramework.UIPanel
    {
        ResLoader mResLoader = ResLoader.Allocate();
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {

        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as MyMotaUIGamePanelData ?? new MyMotaUIGamePanelData();


            GameObject mGameScenePrefa = mResLoader.LoadSync<GameObject>("GameScenePrefab")
                  .Instantiate();


            mResLoader.LoadSync<GameObject>("MyEasyTouchJoystick")
                  .Instantiate();
            mData.Model.MoveSpeed.Value = PlayerPrefs.GetFloat("MoveSpeed", 0.2f);
            Player.Instance.mPlayerData = mData.Model;
        }

        protected override void RegisterUIEvent()
        {
            // MVP模式,数据订阅
           mData.Model.Name.Select(content => "名字: " + content).SubscribeToText(Name);
           mData.Model.CurrntFloor.Select(content => "第 " + content + " 层").SubscribeToText(CurrntFloor);
           mData.Model.Level.Select(content => "等级: " + content).SubscribeToText(Level);
      
           mData.Model.Life.Select(content => "生命: " + content).SubscribeToText(Life);
           mData.Model.Attack.Select(content => "攻击: " + content).SubscribeToText(Attack);
           mData.Model.Defend.Select(content => "防御: " + content).SubscribeToText(Defend);
           mData.Model.Experience.Select(content => "经验: " + content).SubscribeToText(Experience);
           mData.Model.Gold.Select(content => "金币: " + content).SubscribeToText(Gold);
           mData.Model.YellowKey.Select(content => "黄钥匙: " + content).SubscribeToText(YellowKey);
           mData.Model.RedKey.Select(content => "红钥匙: " + content).SubscribeToText(RedKey);
           mData.Model.PurpleKey.Select(content => "紫钥匙: " + content).SubscribeToText(PurpleKey);
           mData.Model.Level.Skip(1).Subscribe(content =>
            {
                mData.Model.Attack.Value += 5;
                mData.Model.Defend.Value += 5;
                mData.Model.Life.Value += 50;
            }
       );

            // UI事件
            BtnContinue.onClick.AddListener(() =>
            {
                GuidePanel.Hide(); // 关闭引导界面
                Player.Instance.mCanMove = true; // 重新让玩家可移动
            });
        }
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
<<<<<<< HEAD
=======
          
>>>>>>> 8207420c391999537d5f8dbc19fe02f937f6ba2d
        }

        protected override void OnHide()
        {
        }
        protected override void OnClose()
        {
          
        }

        protected override void OnBeforeDestroy()
        {
            mResLoader.Recycle2Cache();
            mResLoader = null;
        }

    }
}
