//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using QF.Extensions;
    using QF.Res;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class MyMotaUIGamePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class MyMotaUIGamePanel : QFramework.UIPanel
    {
        ResLoader mResLoader = ResLoader.Allocate();
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {

        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as MyMotaUIGamePanelData ?? new MyMotaUIGamePanelData();

            mResLoader.LoadSync<GameObject>("GameScenePrefab")
                .Instantiate();
            PlayerData.Instance.InitPlayerData();
        }

        protected override void RegisterUIEvent()
        {
            PlayerData.Instance.Name.Select(content => "Ãû×Ö: " + content).SubscribeToText(Name);
            PlayerData.Instance.CurrntFloor.Select(content => "µÚ " + content + " ²ã").SubscribeToText(CurrntFloor);
            PlayerData.Instance.Level.Select(content => "µÈ¼¶: " + content).SubscribeToText(Level);
            PlayerData.Instance.Life.Select(content => "ÉúÃü: " + content).SubscribeToText(Life);
            PlayerData.Instance.Attack.Select(content => "¹¥»÷: " + content).SubscribeToText(Attack);
            PlayerData.Instance.Defend.Select(content => "·ÀÓù: " + content).SubscribeToText(Defend);
            PlayerData.Instance.Experience.Select(content => "¾­Ñé: " + content).SubscribeToText(Experience);
            PlayerData.Instance.Gold.Select(content => "½ð±Ò: " + content).SubscribeToText(Gold);
            PlayerData.Instance.YellowKey.Select(content => "»ÆÔ¿³×: " + content).SubscribeToText(YellowKey);
            PlayerData.Instance.RedKey.Select(content => "ºìÔ¿³×: " + content).SubscribeToText(RedKey);
            PlayerData.Instance.PurpleKey.Select(content => "×ÏÔ¿³×: " + content).SubscribeToText(PurpleKey);

        }
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
            mResLoader.Recycle2Cache();
            mResLoader = null;
        }
    }
}
