//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using QF.Res;
    using QFramework;
    
    
    public class MyMotaUIEndPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class MyMotaUIEndPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as MyMotaUIEndPanelData ?? new MyMotaUIEndPanelData();

            SendMsg(new AudioMusicMsg("end"));
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
            UIMgr.ClosePanel<MyMotaUIGamePanel>();
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
