//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class MyMotaUIHomePanel
    {
        
        public const string NAME = "MyMotaUIHomePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnStart;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnReload;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnSetting;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAbout;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnQuit;
        
        [SerializeField()]
        public UnityEngine.UI.Image AboutPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Text Text;
        
        [SerializeField()]
        public UnityEngine.UI.Image SettingPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Slider SpeedSlider;
        
        private MyMotaUIHomePanelData mPrivateData = null;
        
        public MyMotaUIHomePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new MyMotaUIHomePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnStart = null;
            BtnReload = null;
            BtnSetting = null;
            BtnAbout = null;
            BtnQuit = null;
            AboutPanel = null;
            Text = null;
            SettingPanel = null;
            SpeedSlider = null;
            mData = null;
        }
    }
}
