//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using QF.Extensions;
    using QF.Res;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class MyMotaUIGamePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class MyMotaUIGamePanel : QFramework.UIPanel
    {
        ResLoader mResLoader = ResLoader.Allocate();
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {

        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as MyMotaUIGamePanelData ?? new MyMotaUIGamePanelData();

            mResLoader.LoadSync<GameObject>("GameScenePrefab")
                .Instantiate();
            PlayerData.Instance.InitPlayerData();
            SendMsg(new AudioMusicMsg("bg"));
        }

        protected override void RegisterUIEvent()
        {
            // MVP模式,数据订阅
            PlayerData.Instance.Name.Select(content => "名字: " + content).SubscribeToText(Name);
            PlayerData.Instance.CurrntFloor.Select(content => "第 " + content + " 层").SubscribeToText(CurrntFloor);
            PlayerData.Instance.Level.Select(content => "等级: " + content).SubscribeToText(Level);
            PlayerData.Instance.Life.Select(content => "生命: " + content).SubscribeToText(Life);
            PlayerData.Instance.Attack.Select(content => "攻击: " + content).SubscribeToText(Attack);
            PlayerData.Instance.Defend.Select(content => "防御: " + content).SubscribeToText(Defend);
            PlayerData.Instance.Experience.Select(content => "经验: " + content).SubscribeToText(Experience);
            PlayerData.Instance.Gold.Select(content => "金币: " + content).SubscribeToText(Gold);
            PlayerData.Instance.YellowKey.Select(content => "黄钥匙: " + content).SubscribeToText(YellowKey);
            PlayerData.Instance.RedKey.Select(content => "红钥匙: " + content).SubscribeToText(RedKey);
            PlayerData.Instance.PurpleKey.Select(content => "紫钥匙: " + content).SubscribeToText(PurpleKey);

            // UI事件
            BtnContinue.onClick.AddListener(()=> {
                GuidePanel.Hide(); // 关闭引导界面
                Player.Instance.mCanMove = true; // 重新让玩家可移动
            });


        }
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
            mResLoader.Recycle2Cache();
            mResLoader = null;
        }
    }
}
