//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class MyMotaUITipPanel
    {
        
        public const string NAME = "MyMotaUITipPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text TipText;
        
        private MyMotaUITipPanelData mPrivateData = null;
        
        public MyMotaUITipPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new MyMotaUITipPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TipText = null;
            mData = null;
        }

        internal void DOFade()
        {
            throw new NotImplementedException();
        }
    }
}
