//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using UnityEngine;
    using UnityEngine.UI;
    using UniRx;
    using QF.Extensions;

    public class UIGamePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIGamePanel : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIGamePanelData ?? new UIGamePanelData();

        }

        protected override void RegisterUIEvent()
        {
            PlayerData.Instance.Life.Select(life => "ÉúÃü: " + life).SubscribeToText(LifeText);
            PlayerData.Instance.Attack.Select(life => "¹¥»÷: " + life).SubscribeToText(AttackText);
            PlayerData.Instance.Defend.Select(life => "·ÀÓù: " + life).SubscribeToText(DefendText);
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
