//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIGamePanel
    {
        
        public const string NAME = "UIGamePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text LifeText;
        
        [SerializeField()]
        public UnityEngine.UI.Text AttackText;
        
        [SerializeField()]
        public UnityEngine.UI.Text DefendText;
        
        [SerializeField()]
        public UnityEngine.UI.Text LevelText;
        
        [SerializeField()]
        public UnityEngine.UI.Text ExperienceText;
        
        [SerializeField()]
        public UnityEngine.UI.Text GoldText;
        
        [SerializeField()]
        public UnityEngine.UI.Text tipText;
        
        private UIGamePanelData mPrivateData = null;
        
        public UIGamePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIGamePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            LifeText = null;
            AttackText = null;
            DefendText = null;
            LevelText = null;
            ExperienceText = null;
            GoldText = null;
            tipText = null;
            mData = null;
        }
    }
}
