//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using UnityEngine;
    using UnityEngine.UI;
    using UniRx;
    using QF.Extensions;
    using QF.Res;

    public class UIGamePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIGamePanel : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIGamePanelData ?? new UIGamePanelData();
            this.SendMsg(new AudioMusicMsg("bg", true));

        }

        protected override void RegisterUIEvent()
        {
            Player.Instance.mPlayerData.Life.Select(life => "生命: " + life).SubscribeToText(LifeText);
            Player.Instance.mPlayerData.Attack.Select(life => "攻击: " + life).SubscribeToText(AttackText);
            Player.Instance.mPlayerData.Defend.Select(life => "防御: " + life).SubscribeToText(DefendText);
            Player.Instance.mPlayerData.Level.Select(life => "等级: " + life).SubscribeToText(LevelText);
            Player.Instance.mPlayerData.Experience.Select(life => "经验: " + life).SubscribeToText(ExperienceText);
            Player.Instance.mPlayerData.Gold.Select(life => "金币: " + life).SubscribeToText(GoldText);
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
