//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower
{
    using QFramework;
    using UnityEngine;
    using QF.Res;

    public class UIHomePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIHomePanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIHomePanelData ?? new UIHomePanelData();

            this.SendMsg(new AudioMusicMsg("start", true));
        }

        protected override void RegisterUIEvent()
        {
            BtnStart.onClick.AddListener(() =>
            {
                CloseSelf();
                PlayerData.Instance.InitPlayerData();
                UIMgr.OpenPanel<UIGamePanel>();
            });
            BtnReload.onClick.AddListener(()=>
            {
              //PlayerData.Instance.LoadPlayerData();
            });
            BtnGameInfo.onClick.AddListener(() =>
            {
              
            });
            BtnQuit.onClick.AddListener(() =>
            {
                //PlayerData.Instance.SavePlayerData();
                Application.Quit();
            });
        }
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
