//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Bg_mp3
    {
        public const string BundleName = "bg_mp3";
        public const string BG = "bg";
    }
    public class Boss_mp3
    {
        public const string BundleName = "boss_mp3";
        public const string BOSS = "boss";
    }
    public class Door_mp3
    {
        public const string BundleName = "door_mp3";
        public const string DOOR = "door";
    }
    public class End_mp3
    {
        public const string BundleName = "end_mp3";
        public const string END = "end";
    }
    public class Feixing_mp3
    {
        public const string BundleName = "feixing_mp3";
        public const string FEIXING = "feixing";
    }
    public class Fight_mp3
    {
        public const string BundleName = "fight_mp3";
        public const string FIGHT = "fight";
    }
    public class Prop_mp3
    {
        public const string BundleName = "prop_mp3";
        public const string PROP = "prop";
    }
    public class Shangdian_mp3
    {
        public const string BundleName = "shangdian_mp3";
        public const string SHANGDIAN = "shangdian";
    }
    public class Start_mp3
    {
        public const string BundleName = "start_mp3";
        public const string START = "start";
    }
    public class Talk_mp3
    {
        public const string BundleName = "talk_mp3";
        public const string TALK = "talk";
    }
    public class Uiendpanel_prefab
    {
        public const string BundleName = "uiendpanel_prefab";
        public const string UIENDPANEL = "uiendpanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "uigamepanel";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "uihomepanel";
    }
    public class Uiprefab
    {
        public const string BundleName = "uiprefab";
    }
}
